repos:
-   repo: local
    hooks:
    - id: pytest
      name: Test with Pytest
      language: system
      entry: pytest src
      pass_filenames: false
      always_run: true
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
      name: Remove trailing whitespace
      exclude: ^migrations/
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.4
    hooks:
    - id: autopep8
      name: Run Autopep8 linter
      exclude: ^migrations/

