#application:
#  - gardenbuilder-backend:us-central1:gardenbuilder

runtime: python38

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

env_variables:
  DJANGO_SECRET_KEY: 'e!x2z+3pnm#=qg#8$0_2gzizli#3ez@75l&8$)5_y%nb#xcii3'
