name: garden-builder-backend-ci
on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    container: python:3.8-slim
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      # In testing jobs, all services are automatically available via 
      # docker bridge network, so we can neither expose any port, 
      # nor can we change port and host of the postgres service.
      DB_HOST_LOCAL: postgres
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: 5432
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt
      - name: Run tests
        run: ./manage.py test
  
  Code-Quality:
    name: Code quality
    runs-on: ubuntu-latest
    container: python:3.8-slim
    steps:
      - uses: actions/checkout@v2
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8 to check code quality
        run: flake8 .
