name: garden-builder-backend-ci
on:
  push:
    branches:
      - github-actions-ci-cd

defaults:
  run:
    shell: bash

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    container: python:3.8-slim
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: gardenbuilder
    env:
      DB_NAME: gardenbuilder
      DB_USER: root
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST_LOCAL: postgres
      DB_PORT: 5432
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt
      - name: Run tests
        run: ./manage.py test
  
  Code-Quality:
    name: Code quality
    runs-on: ubuntu-latest
    container: python:3.8-slim
    steps:
      - uses: actions/checkout@v2
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8 to check code quality
        run: flake8 .