name: garden-builder-backend-ci
on: 
  push:
    branches:
      - github-actions-ci-cd

defaults:
  run:
    shell: bash

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    container: python:3.8-slim
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: gardenbuilder
    env:
      DB_NAME: gardenbuilder
      DB_USER: root
      DB_PASSWORD: secret
      DB_HOST_LOCAL: postgres
      DB_PORT: 5432
      DJANGO_SECRET_KEY: secretKeyHere
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
      - name: Run tests
        run: |
          cd src
          ./manage.py test